# Generated by Django 6.0.1 on 2026-01-30 07:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0003_category_alter_product_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_size', models.CharField(help_text='500ml, 1L, 5kg', max_length=50)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='application_method',
            field=models.CharField(default=django.utils.timezone.now, help_text='Soil / Foliar / Drip', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage',
            field=models.CharField(default=django.utils.timezone.now, help_text='Dosage per acre or litre', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Requires prescription or special approval'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_period',
            field=models.CharField(blank=True, help_text='Waiting period after application', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='product',
            name='crops',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.crop'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'pack_size')},
        ),
    ]
